### ISSUE TITLE
Does not work on VS2019

### ISSUE THREAD

**Issue by danypd69** [wakatime/visualstudio-wakatime#102]
I get this error in the output window when starting VS2019 16.5.4 and the extension does not load.

[WakaTime Info 12:40:14 PM] Initializing WakaTime v10.0.3
[WakaTime HandledException 12:40:14 PM] Are you behind a proxy? Try setting a proxy in WakaTime Settings with format https://user:pass@host:port. Exception Traceback:: System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: The process cannot access the file 'C:\Users\daniele\AppData\Roaming\WakaTime\wakatime-cli.zip' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at WakaTime.Dependencies.DownloadFile(String url, String saveAs)
   at WakaTime.Dependencies.DownloadAndInstallCli()
   at WakaTime.WakaTimePackage.InitializeAsync()
[WakaTime Info 12:40:14 PM] Finished initializing WakaTime v10.0.3

**Comment by danypd69** [comment]
Works after restarting computer.
