### ISSUE TITLE
Visual Studio 2019 Installation Error

### ISSUE THREAD

**Issue by KennyTK** [wakatime/visualstudio-wakatime#130]
I'm attempting to install the plugin into the following visual studio instance.
```
Microsoft Visual Studio Community 2019
Version 16.10.4
VisualStudio.16.Release/16.10.4+31515.178
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA917
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   16.0.31130.00
Microsoft Office Developer Tools for Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62106.24090
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Windows Template Studio   4.1.21179.1
Windows Template Studio quickly builds a UWP app, using a wizard-based UI to turn your needs into a foundation of Windows 10 patterns and best practices.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.
```

Upon restart I'm met with the following dialogues. 

![image](https://user-images.githubusercontent.com/16214078/173961891-6c475fc4-c9f0-4508-a212-39b8700d02ef.png)

![image](https://user-images.githubusercontent.com/16214078/173961938-04998cd6-d205-4251-86a1-8e17c282aed2.png)

I'm unsure what the root cause could be.

**Truncated Log:**
```6/15/2022 8:02:50 PM - Microsoft VSIX Installer
6/15/2022 8:02:50 PM - -------------------------------------------
6/15/2022 8:02:50 PM - vsixinstaller.exe version:
6/15/2022 8:02:50 PM - 16.11.12
6/15/2022 8:02:50 PM - -------------------------------------------
6/15/2022 8:02:50 PM - Command line parameters:
6/15/2022 8:02:50 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:16.10.31515.178,/appidname:Microsoft Visual Studio Community 2019,/culture:en-US,/noep,C:\Users\KTrelfa.EXECUTIVE\AppData\Local\Temp\VSIXmtdmuqfq.vsix
6/15/2022 8:02:50 PM - -------------------------------------------
6/15/2022 8:02:50 PM - Microsoft VSIX Installer
6/15/2022 8:02:50 PM - -------------------------------------------
6/15/2022 8:02:51 PM - Found setup instance ec33d125 but not in launchable state.
6/15/2022 8:02:51 PM - Initializing Install...
6/15/2022 8:02:52 PM - Extension Details...
6/15/2022 8:02:52 PM - 	Identifier         : 52d9c3ff-c893-408e-95e4-d7484ec7fa47
6/15/2022 8:02:52 PM - 	Name               : WakaTime
6/15/2022 8:02:52 PM - 	Author             : WakaTime
6/15/2022 8:02:52 PM - 	Version            : 13.0.0
6/15/2022 8:02:52 PM - 	Description        : Metrics, insights, and time tracking automatically generated from your programming activity.
6/15/2022 8:02:52 PM - 	Locale             : en-US
6/15/2022 8:02:52 PM - 	MoreInfoURL        : https://github.com/wakatime/visualstudio-wakatime
6/15/2022 8:02:52 PM - 	InstalledByMSI     : False
6/15/2022 8:02:52 PM - 	SupportedFrameworkVersionRange : [4.8,)
6/15/2022 8:02:52 PM - 
6/15/2022 8:02:52 PM - 	SignatureState     : Unsigned
6/15/2022 8:02:52 PM - 	Supported Products : 
6/15/2022 8:02:52 PM - 		Microsoft.VisualStudio.Community
6/15/2022 8:02:52 PM - 			Version : [15.0,17.0)
6/15/2022 8:02:52 PM - 		Microsoft.VisualStudio.Pro
6/15/2022 8:02:52 PM - 			Version : [15.0,17.0)
6/15/2022 8:02:52 PM - 		Microsoft.VisualStudio.Enterprise
6/15/2022 8:02:52 PM - 			Version : [15.0,17.0)
6/15/2022 8:02:52 PM - 		Microsoft.VisualStudio.IntegratedShell
6/15/2022 8:02:52 PM - 			Version : [15.0,17.0)
6/15/2022 8:02:52 PM - 		Microsoft.VisualStudio.Ultimate
6/15/2022 8:02:52 PM - 			Version : [15.0,17.0)
6/15/2022 8:02:52 PM - 		Microsoft.VisualStudio.Premium
6/15/2022 8:02:52 PM - 			Version : [15.0,17.0)
6/15/2022 8:02:52 PM - 		Microsoft.VisualStudio.VSLS
6/15/2022 8:02:52 PM - 			Version : [15.0,17.0)
6/15/2022 8:02:52 PM - 
6/15/2022 8:02:52 PM - 	References         : 
6/15/2022 8:02:52 PM - 		-------------------------------------------------------
6/15/2022 8:02:52 PM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
6/15/2022 8:02:52 PM - 		Name         : Visual Studio MPF 14.0
6/15/2022 8:02:52 PM - 		Version      : [14.0,17.0)
6/15/2022 8:02:52 PM - 		MoreInfoURL  : 
6/15/2022 8:02:52 PM - 		Nested       : No
6/15/2022 8:02:52 PM - 
6/15/2022 8:02:52 PM - 	Prerequisites      : 
6/15/2022 8:02:52 PM - 		-------------------------------------------------------
6/15/2022 8:02:52 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/15/2022 8:02:52 PM - 		Name         : Visual Studio core editor
6/15/2022 8:02:52 PM - 		Version      : [15.0,17.0)
6/15/2022 8:02:52 PM - 
6/15/2022 8:02:52 PM - Signature Details...
6/15/2022 8:02:52 PM - 	Extension is not signed.
6/15/2022 8:02:52 PM - 
```
_-skipping file discovery information-_
```
6/15/2022 8:03:38 PM - Beginning to install extension to Microsoft Visual Studio Community 2019...
6/15/2022 8:03:38 PM - Found setup instance ec33d125 but not in launchable state.
6/15/2022 8:03:38 PM - Install Error : System.InvalidOperationException: Cannot find setup engine instance.
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineUtility.GetCurrentSetupInstance(IEngineHost engineHost)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.CreateEngine(IEngineHost engineHost, IServiceProvider serviceProvider, InstallFlags installFlags)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

**Comment by KennyTK** [comment]
I've solved this by updating to a newer version of visual studio.
