### ISSUE TITLE
Error installing dependencies

### ISSUE THREAD

**Issue by chenboshuo** [wakatime/visualstudio-wakatime#138]
VS 2022, Windows 11(WinDev2212 for virtualbox), when srart vs,I get the following error message.
```
15:51:32:463	[WakaTime HandledException 03:51:31 PM] Error installing dependencies: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:443
15:51:32:463	   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
15:51:32:463	   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
15:51:32:463	   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
15:51:32:463	   --- End of inner exception stack trace ---
15:51:32:463	   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
15:51:32:463	   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
15:51:32:463	   --- End of inner exception stack trace ---
15:51:32:463	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:51:32:463	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:51:32:463	   at WakaTime.Shared.ExtensionUtils.Dependencies.<DownloadFile>d__22.MoveNext()
15:51:32:463	--- End of stack trace from previous location where exception was thrown ---
15:51:32:463	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:51:32:463	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:51:32:463	   at WakaTime.Shared.ExtensionUtils.Dependencies.<InstallCli>d__11.MoveNext()
15:51:32:463	--- End of stack trace from previous location where exception was thrown ---
15:51:32:463	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:51:32:463	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:51:32:463	   at WakaTime.Shared.ExtensionUtils.Dependencies.<CheckAndInstallCli>d__9.MoveNext()
15:51:32:463	--- End of stack trace from previous location where exception was thrown ---
15:51:32:463	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:51:32:463	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:51:32:463	   at WakaTime.Shared.ExtensionUtils.Dependencies.<CheckAndInstall>d__8.MoveNext()
15:51:32:463	--- End of stack trace from previous location where exception was thrown ---
15:51:32:463	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:51:32:463	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:51:32:463	   at WakaTime.Shared.ExtensionUtils.WakaTime.<InitializeAsync>d__13.MoveNext()
```
Since it like a network error, I try to `ping`:
![image](https://user-images.githubusercontent.com/43953268/215702393-77b39aa0-c529-4274-af5d-21db0767f758.png)

How could I do next? Thanks for your attention.

**Comment by SCC-Robert** [comment]
Is wakatime abandoned? This has been open for a month with nothing and no reply or comment.

**Comment by alanhamlett** [comment]
@gandarez is the lead on the Visual Studio plugin.

My first guess whenever there's a network issue is a proxy could be required to connect to the internet?

**Comment by alanhamlett** [comment]
Looks like it's trying to use a proxy `127.0.0.1` from the error message. Do you have a proxy configured in your `~/.wakatime.cfg` file?

**Comment by chenboshuo** [comment]
@alanhamlett 
> Looks like it's trying to use a proxy 127.0.0.1 from the error message. Do you have a proxy configured in your ~/.wakatime.cfg file?

 No, the configure file only include my API key

**Comment by alanhamlett** [comment]
Does Visual Studio have a proxy configured? It might try to use that. We can check by turning on debug mode so more logs are printed to your Output Window or ActivityLog.xml:

https://github.com/wakatime/visualstudio-wakatime#troubleshooting

**Comment by gandarez** [comment]
@chenboshuo any update on this?

**Comment by gandarez** [comment]
Please update to latest version. Feel free to reopen this issue.
