### ISSUE TITLE
System.Runtime.InteropServices.COMException at EnvDTE._DTE.get_Solution()

### ISSUE THREAD

**Issue by sinkien** [wakatime/visualstudio-wakatime#28]
I'm using VS2013 Premium, WakaTIme plugin version 5.0.4.
Besides ticket  #26, this exception is still popping up and killing Visual Studio. I'm working on WPF application, and when I'm in the designer and I'll try to use scrollbars to move around the designer's view, :boom: , Visual Studio dies. If I take a look into event log, I see this:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
Stack:
   at EnvDTE._DTE.get_Solution()
   at WakaTime.WakaTimePackage.GetProjectName()
   at WakaTime.WakaTimePackage.SendHeartbeat(System.String, Boolean)
   at WakaTime.WakaTimePackage+<>c__DisplayClass3.<HandleActivity>b__2()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by gandarez** [comment]
Please update #25 with this error.

**Comment by alanhamlett** [comment]
Let's leave this issue open, but link it to #25 so I can close both at the same time. I love GH issues!

**Comment by alanhamlett** [comment]
Just released v5.0.5 of the extension. Can someone confirm it's fixed after updating?

**Comment by gandarez** [comment]
@sinkien could you please do test?

**Comment by sinkien** [comment]
@gandarez I've installed this new version (5.0.5) into VS2013 Premium and VS2015 Enterprise and after two days of my usual work, it seems finally fixed. Good job :+1:
