### ISSUE TITLE
Not working on system with some special encoding.

### ISSUE THREAD

**Issue by yyjdelete** [wakatime/visualstudio-wakatime#33]
language:zh-cn, default encoding: GBK
```
[Wakatime Debug 10:46:44 上午] ["C:\Python34\pythonw", "C:\Users\**\AppData\Roaming\Microsoft Corporation\Microsoft® Visual Studio® 2015\14.0.23107.0\wakatime-master\wakatime\cli.py", --key", ******", --file", ******.cs", --plugin", visualstudio/14.0 visualstudio-wakatime/5.0.6", --project", EapolLogin"]
[Wakatime Debug 10:46:44 上午] CLI STDOUT: 
[Wakatime Debug 10:46:44 上午] CLI STDERR: Traceback (most recent call last):
  File "<encoding error>", line 15, in <module>
ImportError: No module named 'wakatime'
```

**Comment by yyjdelete** [comment]
Also failed with CMD, but it's OK after manually run

C:\Python34\python setup.py install

what's wrong with that?

**Comment by yyjdelete** [comment]
something still wrong with the python,
```
Traceback (most recent call last):
  File "cli.py", line 18, in <module>
    sys.exit(wakatime.main(sys.argv))
  File "C:\Users\**\AppData\Roaming\Microsoft Corporation\Microsoft\xae Visual Studio\xae 2**5\14.0.23107.0\wakatime-master\wakatime\base.py", line 460, in main

    if send_heartbeat(**kwargs):
  File "C:\Users\**\AppData\Roaming\Microsoft Corporation\Microsoft\xae Visual Studio\xae 2**5\14.0.23107.0\wakatime-master\wakatime\base.py", line 377, in send_heartbeat
    proxies=proxies)
  File "C:\Users\**\AppData\Roaming\Microsoft Corporation\Microsoft\xae Visual Studio\xae 2**5\14.0.23107.0\wakatime-master\wakatime\packages\requests\sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\**\AppData\Roaming\Microsoft Corporation\Microsoft\xae Visual Studio\xae 2**5\14.0.23107.0\wakatime-master\wakatime\packages\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\**\AppData\Roaming\Microsoft Corporation\Microsoft\xae Visual Studio\xae 2**5\14.0.23107.0\wakatime-master\wakatime\packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\**\AppData\Roaming\Microsoft Corporation\Microsoft\xae Visual Studio\xae 2**5\14.0.23107.0\wakatime-master\wakatime\packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Users\**\AppData\Roaming\Microsoft Corporation\Microsoft\xae Visual Studio\xae 2**5\14.0.23107.0\wakatime-master\wakatime\packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Users\**\AppData\Roaming\Microsoft Corporation\Microsoft\xae Visual Studio\xae 2**5\14.0.23107.0\wakatime-master\wakatime\packages\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Users\**\AppData\Roaming\Microsoft Corporation\Microsoft\xae Visual Studio\xae 2**5\14.0.23107.0\wakatime-master\wakatime\packages\requests\packages\urllib3\connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "C:\Users\**\AppData\Roaming\Microsoft Corporation\Microsoft\xae Visual Studio\xae 2**5\14.0.23107.0\wakatime-master\wakatime\packages\requests\packages\urllib3\connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "C:\Users\**\AppData\Roaming\Microsoft Corporation\Microsoft\xae Visual Studio\xae 2**5\14.0.23107.0\wakatime-master\wakatime\packages\requests\packages\urllib3\util\ssl_.py", line 256, in ssl_wrap_socket
    context.load_verify_locations(ca_certs)
TypeError: cafile should be a valid filesystem path
```

**Comment by yyjdelete** [comment]
It seems something is wrong in requests, alreay post an issue to requests [#2688](https://github.com/kennethreitz/requests/issues/2688)

**Comment by alanhamlett** [comment]
@yyjdelete yep, looks related to kennethreitz/requests#2688. I'll help debug it there.

**Comment by alanhamlett** [comment]
@yyjdelete can you delete the `wakatime-master` folder on your machine so the WakaTime plugin will update to the latest version of wakatime cli? This bug might be fixed with afc012ab6361d7d12e1b9519a4b5a3f14c559bd0. Would you mind testing the latest version to see if it's fixed?

**Comment by yyjdelete** [comment]
Still the same, and the below en/decode seems work well for me(not sure for other encoding)
```python
        certdir = os.path.dirname(
            __file__.encode('utf8').decode(sys.getfilesystemencoding())
            if is_py3 else
            __file__
        )
```

**Comment by alanhamlett** [comment]
@yyjdelete that's great! Wish I had seen this earlier... just came across a similar fix in wakatime/wakatime#32. Does the current wakatime cli work for you?

**Comment by yyjdelete** [comment]
This is also works for me.

**Comment by alanhamlett** [comment]
Finally, this is great!

It's better to not decode in our fix because that could cause an exception. However, `os.path.dirname` could be implicitly decoding. I'll just leave it the way the code is now, since it's working.
