### ISSUE TITLE
Visual Studio Express 2015 for Desktop 

### ISSUE THREAD

**Issue by meNoob** [wakatime/visualstudio-wakatime#63]
WakaTime-express-v8.0.5.vsix
Wont install on Visual Studio Express 2015 for Desktop

Error Log

```Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
- Visual Studio MPF
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
```

**Comment by alanhamlett** [comment]
Can you try:

1. clone this repo
2. open the project in Visual Studio Express 2015
3. switch to the Express build profile
4. build the project
5. run the compiled vsix file inside Debug/Express folder

**Comment by meNoob** [comment]
Honestly I wasn't able to import it to VS Express 2015 for Win Desk version 14.0.25431.01 Update 3

The only feedback I got is:
http://prntscr.com/dl8enx

**Comment by alanhamlett** [comment]
That means the Solution is for a different version of Visual Studio. You can edit this line to say `14` instead of `15`, then re-open the Solution and Visual Studio should automatically upgrade the project to your VS version:
https://github.com/wakatime/visualstudio-wakatime/blob/1bd011595b39c2879bd35317350fe95b326f3582/WakaTime/WakaTime.csproj#L4
