### ISSUE TITLE
Error when starting in VS 2017 and no time is logged

### ISSUE THREAD

**Issue by 06needhamt** [wakatime/visualstudio-wakatime#68]
Hi 

I am facing an issue with the wakatime VS2017 extension the following error occurs upon starting the IDE and no time is logged.

``` c#

[WakaTime Info 10:42:59 AM] Initializing WakaTime v8.0.6
[WakaTime Info 10:43:00 AM] Current wakatime-cli version is 8.0.3
[WakaTime Info 10:43:00 AM] Checking for updates to wakatime-cli...
[WakaTime HandledException 10:43:21 AM] Exception when checking current wakatime cli version: : System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 90.207.238.183:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at WakaTime.Constants.<>c.<.cctor>b__8_0()
[WakaTime Info 10:43:21 AM] Found an updated wakatime-cli v
[WakaTime Info 10:43:27 AM] Finished initializing WakaTime v8.0.6
```

Let me know if you need any more information

**Comment by alanhamlett** [comment]
The first line of the error says it's connecting to IP `90.207.238.183`, but that IP is not the IP address of GitHub:

```
Exception when checking current wakatime cli version: System.Net.WebException ... host has failed to respond 90.207.238.183:443
```

Do you use a proxy to connect to the internet?

**Comment by 06needhamt** [comment]
No, I don't
But I have been having some issues connecting to GitHub over the last few days which seem to be resolved today and this error is no longer being thrown so this issue seems to be fixed

**Comment by alanhamlett** [comment]
Ok that would cause these errors. Glad it's resolved, and let me know if we need to reopen in the future.
