### ISSUE TITLE
Proxy Settings not working on visual studio

### ISSUE THREAD

**Issue by sandeepkru** [wakatime/visualstudio-wakatime#72]
I keep getting below error irrespective of my proxy settings in $HOME/.wakatime.cfg file, other editors (emacs and atom) work fine without any proxy settings except visual studio. $HOME/.wakatime.log doesn't contain any logs related to visual studio related. Error details are below
```
[WakaTime Debug 10:24:13 AM] Downloading wakatime-cli...
[WakaTime Debug 10:24:13 AM] No proxy will be used. It's either not set or badly formatted.
[WakaTime HandledException 10:24:13 AM] Are you behind a proxy? Try setting a proxy in WakaTime Settings with format https://user:pass@host:port. Exception Traceback:: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at WakaTime.Dependencies.DownloadAndInstallCli()
   at WakaTime.WakaTimePackage.InitializeAsync()
[WakaTime Info 10:24:13 AM] Finished initializing WakaTime v8.0.6
```
Am I missing anything obvious here?

**Comment by sandeepkru** [comment]
As workaround looking at code [Constants.cs](https://github.com/wakatime/visualstudio-wakatime/blob/master/WakaTime/Constants.cs), I've downloaded [wakatime-cli](https://github.com/wakatime/wakatime/archive/master.zip") and placed in it's expected location. New debug messages show that it seems pushing correctly, but I couldn't find values on dashboard though.
```
[WakaTime Info 01:35:57 PM] wakatime-cli is up to date.
[WakaTime Info 01:35:57 PM] Finished initializing WakaTime v8.0.6
[WakaTime Debug 01:36:05 PM] ["\AppData\Roaming\WakaTime\wakatime-master\wakatime\cli.py", "--key", "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX4726", "--entity", "file.cpp", "--time", "1519940161.953178", "--plugin", "visualstudio/12.0 visualstudio-wakatime/8.0.6", "--project", "dirs"]
[WakaTime Debug 01:36:13 PM] ["\AppData\Roaming\WakaTime\python\pythonw", "\AppData\Roaming\WakaTime\wakatime-master\wakatime\cli.py", "--key", "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX4726", "--entity", "file.h", "--time", "1519940168.658049", "--plugin", "visualstudio/12.0 visualstudio-wakatime/8.0.6", "--project", "dirs"]
```
