### ISSUE TITLE
Problem behind corporate proxy

### ISSUE THREAD

**Issue by Jazzman82** [wakatime/visualstudio-wakatime#76]
**We are behind corporate proxy, so without any configuration in waka-time I see the following error in VS-Output-Window:**

[WakaTime HandledException 10:23:57 AM] Exception when checking current wakatime cli version: : System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat 151.101.192.133:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at WakaTime.Constants.<>c.<.cctor>b__8_0()
[WakaTime Info 10:23:57 AM] Found an updated wakatime-cli v
[WakaTime Debug 10:23:57 AM] Downloading wakatime-cli...
[WakaTime Debug 10:23:57 AM] No proxy will be used. It's either not set or badly formatted.
[WakaTime HandledException 10:24:39 AM] Are you behind a proxy? Try setting a proxy in WakaTime Settings with format https://user:pass@host:port. Exception Traceback:: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat 192.30.253.113:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at WakaTime.Dependencies.DownloadFile(String url, String saveAs)
   at WakaTime.Dependencies.DownloadAndInstallCli()
   at WakaTime.WakaTimePackage.InitializeAsync()
[WakaTime Info 10:24:39 AM] Finished initializing WakaTime v8.0.7

**When I configure proxy, the error in VS is gone but it an proxy error is logged in the .wakatime.log and no data is sent.**
{'ProxyError': \"HTTPSConnectionPool(host='api.wakatime.com', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',)))\", 'traceback': 'Traceback (most recent call last)

**It seems as if the proxy-settings only affect the vs-plugin but not the cli....**

**Comment by gandarez** [comment]
@Jazzman82 update to latest version and let me know if it's working.

**Comment by Jazzman82** [comment]
I just checked again and with the latest version from marketplace (10.0.3) it works
